### ISSUE TITLE
MapVC loaded from Nib

### ISSUE THREAD

**Issue by aferre** [RVLVR/REVClusterMap#1]
Hi

Thanks for sharing this, it seems like quite a nice API.

I just tried it and failed because I think it doesn't support a Viewcontroller loaded from nib is this right?

**Comment by RVLVR** [comment]
This controller is not designed to work with a nib.
But if you want to the changes aren't that difficult. you need to alter it a bit.
Personally i'm not a big fan of nibs, thats why i did not included it in my source. But its up to you.

**Comment by aferre** [comment]
OK thanks

**Comment by SushilSharma12** [comment]
https://github.com/RVLVR/REVClusterMap/issues/14
Follow this link.. You will get some idea from the answer
