### ISSUE TITLE
addAnnotation: with a single REVClusterPin deletes all the pins

### ISSUE THREAD

**Issue by lupidan** [RVLVR/REVClusterMap#13]
The original method inherited from MKMapView seems to be messing up your clustering info. I think it's because it's not implemented in your custom REVClusterMapView.

I could solve it by adding the single pin using addAnnotations: with an array of one single object, so no problem. But I think It could be a nice feature to add to your component :)

**Comment by fabiosoft** [comment]
i'am getting crazy! do not use `addAnnotation:` compose the array then add to the map

**Comment by guru78** [comment]
create object of REVClusterPin and add it to array of annotations..

**Comment by key** [comment]
+1
